name: CloudApp Azure Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - 'dev'
      - 'main'
    paths:
      - cloudapp/azure/**
      - cloudapp/app.py
      - cloudapp/templates/**
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'dev'
    paths:
      - cloudapp/azure/**
      - cloudapp/app.py
      - cloudapp/templates/**

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 

    - name: Deploy to Azure Functions
      uses: azure/functions-action@v1
      with:
        app-name: YourFunctionAppName
        package: ./cloudapp
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}

